#!/bin/sh

killSkippyXd() {

  killall 'skippy-xd'

  if [ -f '/tmp/skippy-xd-fifo' ]
  then
    rm /tmp/skippy-xd-fifo
  fi

}

toggleSkippyXd() {

  skippyConfig="$1"
  psSkippyOut=`ps aux | grep '[s]kippy-xd '`
  psSkippyActivateOut=`ps aux | grep '[s]kippy-xd --activate-window-picker'`
  psSkippyToggleOut=`ps aux | grep '[s]kippy-xd --toggle-window-picker'`

  ## IF, when calling skippy-xd, to start the window picker, 
  ## a process to do so already exists, then skippy-xd is stuck, 
  ## so we must clear its queue and restart its daemon.
  ## ELSE, if the skippy-xd daemon has not been started,
  ## we should start it.  

  if [ ! -z "$psSkippyActivateOut" ] || [ ! -z "$psSkippyToggleOut" ]
  then
    killSkippyXd
    skippy-xd --start-daemon --config "$skippyConfig" &
  elif [ -z "$psSkippyOut" ]
  then
    skippy-xd --start-daemon --config "$skippyConfig" &
  fi

  skippy-xd --toggle-window-picker

  exit $?

}

(toggleSkippyXd "$@")
